services:
  web:
    build: .
    ports:
      - "8083:8083"
#    depends_on:
#      - db
#    networks:
#      - dash-test

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD="example"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - dash-test
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:

#networks:
#  dash-test:
#    driver: bridge
